# Generated by Django 6.0.2 on 2026-03-23 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Projects',
        ),
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Task',
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
